let cleanersWage = 40000;
let vocalistWage = 22000;
console.log(`вечерний уборщик, имея голос и педагогическое образование, может зарабатывать ${cleanersWage + vocalistWage} рублей`);
let cityName = 'Владивосток ';
let year = 2000;
console.log(`название известной песни ${cityName + year}`);
let messengersTime = 128;
let photoLike = 254;
let vkRead = 137;
let youtubeStandUp = 201;
console.log(`Русалка прокрастинировала ${(messengersTime + photoLike + VKread + YoutubeStandUp) / 60} часов`);
console.log(2 ** 5);
console.log(`Нужно бежать со всех ног, чтобы только оставаться на месте, а чтобы куда-то попасть, надо бежать как минимум вдвое быстрее!`);
const greetings = "Привет";
const name = "Кот";
console.log(`${greetings}, ${name}!`);
let time;
time = 34;
console.log('Старт поездки. Осталось минут: ' + time);
time -= 15;
console.log(`Немного сторис в соцсетях. Осталось минут: ${time}`);
time -= 10;
console.log(`Немного не новостей, но событий. Осталось минут: ${time}`);
time = '0';
console.log(`Осталось минут: ${time}`);
console.log(`Вы приехали. Добро пожаловать в Москву.`);
let fahrenheit = 451;
let celsius = (fahrenheit - 32) / 1.8;
console.log(`${fahrenheit} градуса по Фаренгейту — это ${celsius} градуса по Цельсию.`);